version: 2
executorType: machine
jobs:
  build:
    working_directory: ~/rcj-react
    steps:
      - checkout
      - run:
          name: Docker Build
          command: |
            docker build -t ${GCR_PATH}/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} .
      - run:
          name: Decode GCloud Credentials
          command: |
            echo ${GOOGLE_AUTH} | base64 -i --decode > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud docker -- push ${GCR_PATH}/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build